import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/build-beacons',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/overview',
        'architecture/teamserver',
        'architecture/operator-client',
        'architecture/beacons',
        'architecture/protocol',
        'architecture/persistence',
        'architecture/realtime-auth',
      ],
    },
    {
      type: 'category',
      label: 'Operator Guide',
      collapsed: false,
      items: [
        'operator/console',
        'operator/sessions',
        'operator/listeners',
        'operator/build-page',
        'operator/file-browser',
        'operator/loot-and-events',
        'operator/mcp',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Identity / Target',
          collapsed: false,
          items: [
            'commands/whoami',
            'commands/id',
            'commands/hostname',
            'commands/domain',
            'commands/getpid',
            'commands/getintegrity',
            'commands/sysinfo',
            'commands/drives',
            'commands/uptime',
          ],
        },
        {
          type: 'category',
          label: 'Filesystem',
          collapsed: false,
          items: [
            'commands/pwd',
            'commands/cd',
            'commands/ls',
            'commands/cat',
            'commands/stat',
            'commands/mkdir',
            'commands/rm',
            'commands/rmdir',
            'commands/cp',
            'commands/mv',
            'commands/chmod',
          ],
        },
        {
          type: 'category',
          label: 'Process / Services',
          collapsed: false,
          items: [
            'commands/ps',
            'commands/kill',
            'commands/services',
            'commands/schtasks-enum',
            'commands/safe-harbor',
          ],
        },
        {
          type: 'category',
          label: 'Network / Pivoting',
          collapsed: false,
          items: [
            'commands/ipconfig',
            'commands/ifconfig',
            'commands/arp',
            'commands/netstat',
            'commands/dns',
            'commands/xpipe',
            'commands/curl',
            'commands/portscan',
            'commands/socks5',
            'commands/interactive',
          ],
        },
        {
          type: 'category',
          label: 'Domain / Directory',
          collapsed: false,
          items: [
            'commands/ldapsearch',
            'commands/adcs_enum',
            'commands/password-policy',
            'commands/net-shares',
            'commands/local-sessions',
            'commands/netloggedon',
          ],
        },
        {
          type: 'category',
          label: 'Privilege / Credentials',
          collapsed: false,
          items: [
            'commands/privs',
            'commands/groups',
            'commands/priv-always-install-elevated',
            'commands/priv-autologon',
            'commands/priv-credential-manager',
            'commands/priv-hijackable-path',
            'commands/priv-modifiable-autorun',
            'commands/priv-modifiable-service',
            'commands/priv-powershell-history',
            'commands/priv-token-privileges',
            'commands/priv-uac-status',
            'commands/priv-unquoted-service-path',
          ],
        },
        {
          type: 'category',
          label: 'Host Data / Registry',
          collapsed: false,
          items: [
            'commands/env',
            'commands/getenv',
            'commands/clipboard',
            'commands/reg_query',
            'commands/reg_set',
            'commands/regsession',
            'commands/msi-search',
          ],
        },
        {
          type: 'category',
          label: 'SQL Server',
          collapsed: false,
          items: [
            'commands/sql-1434udp',
            'commands/sql-info',
            'commands/sql-whoami',
            'commands/sql-impersonate',
            'commands/sql-links',
            'commands/sql-users',
            'commands/sql-databases',
            'commands/sql-tables',
            'commands/sql-columns',
            'commands/sql-rows',
            'commands/sql-search',
            'commands/sql-query',
            'commands/sql-agentstatus',
            'commands/sql-checkrpc',
          ],
        },
        {
          type: 'category',
          label: 'Linux Collection / Remote',
          collapsed: false,
          items: [
            'commands/triagedirectory',
            'commands/ssh',
          ],
        },
        {
          type: 'category',
          label: 'Execution / Modules',
          collapsed: false,
          items: [
            'commands/shell',
            'commands/runas',
            'commands/execute-assembly',
            'commands/inline-assembly',
            'commands/bof-execute',
          ],
        },
        {
          type: 'category',
          label: 'Libraries',
          collapsed: false,
          items: [
            'commands/assembly-upload',
            'commands/assembly-list',
            'commands/assembly-delete',
            'commands/bof-upload',
            'commands/bof-list',
          ],
        },
        {
          type: 'category',
          label: 'Transfer / Control',
          collapsed: false,
          items: [
            'commands/download',
            'commands/upload',
            'commands/sleep',
            'commands/exit',
            'commands/clear',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Beacon Guide',
      collapsed: false,
      items: [
        'beacons/overview',
        'beacons/session-mode',
        'beacons/file-transfer',
        'beacons/socks5',
        'beacons/bof-execution',
        'beacons/execute-assembly',
        'beacons/inline-assembly',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: false,
      items: [
        'development/repository-layout',
        'development/build-and-test',
        'development/rules',
        'development/api-reference',
        'development/protocol-tasks',
        'development/release-process',
      ],
    },
    {
      type: 'category',
      label: 'Security Model',
      collapsed: false,
      items: [
        'security/authorized-use',
        'security/operator-security',
        'security/crypto',
        'security/hardening',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: false,
      items: [
        'troubleshooting/common-issues',
        'troubleshooting/build-errors',
        'troubleshooting/beacon-connectivity',
      ],
    },
  ],
};

export default sidebars;
